// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzprhtegclqmcbmryqcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cHJodGVnY2xxbWNibXJ5cWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDY2NjUsImV4cCI6MjA2ODMyMjY2NX0.JMIbch0sQ-Q-UAt8AV9v1MYz-C4yKhWgxqten4K6x9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});